# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tem_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(709, 268)
        MainWindow.setMinimumSize(QtCore.QSize(709, 268))
        MainWindow.setMaximumSize(QtCore.QSize(709, 268))
        MainWindow.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 0, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.comboSelectItem = QtWidgets.QComboBox(self.centralwidget)
        self.comboSelectItem.setGeometry(QtCore.QRect(110, 110, 511, 31))
        self.comboSelectItem.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.comboSelectItem.setObjectName("comboSelectItem")
        self.comboSelectItem.addItem("")
        self.comboSelectItem.addItem("")
        self.comboSelectItem.addItem("")
        self.comboSelectItem.addItem("")
        self.comboSelectItem.addItem("")
        self.bnt_next = QtWidgets.QPushButton(self.centralwidget)
        self.bnt_next.setGeometry(QtCore.QRect(470, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bnt_next.setFont(font)
        self.bnt_next.setStyleSheet("color: rgb(255, 255, 255);")
        self.bnt_next.setObjectName("bnt_next")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matemática Computacional"))
        self.label.setText(_translate("MainWindow", "Matemática Computacional"))
        self.comboSelectItem.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.comboSelectItem.setItemText(0, _translate("MainWindow", "Seleciona um Item"))
        self.comboSelectItem.setItemText(1, _translate("MainWindow", "Método Newton Raphson"))
        self.comboSelectItem.setItemText(2, _translate("MainWindow", "Método Bisseção"))
        self.comboSelectItem.setItemText(3, _translate("MainWindow", "Método Posição Falsa"))
        self.comboSelectItem.setItemText(4, _translate("MainWindow", "Método Iterativo Linear"))
        self.bnt_next.setText(_translate("MainWindow", "Avançar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
